### ISSUE TITLE
Use Lint.getLintId() as hitid

### ISSUE THREAD

**Issue by sualeh** [adriens/schemacrawler-additional-command-lints-as-csv#3]
Use `Lint.getLintId()` as hitid

**Comment by adriens** [comment]
You mean that `LintId` is a univesal way of referencing a given lint hit ?... This field is not the id of the Lint (like a `NoPrimaryKey`).

**Comment by adriens** [comment]
I mean : the `LintId` is the same accross all runs, while the `hitid` is the unique hit of a given `LintId` on a given database, on a given environment, at a given instant. You'll never be able to get the same `hitid` twice. That's the meaning of this field....like a universal revision number.

**Comment by sualeh** [comment]
`Lint` has two fields, lintId, and linterId. A new `lintId` is assigned per lint, per run, and matches what you are calling `hitid`. `linterId` is a unique identifier for a linter, and is the id of the linter that created the lint. A linter may create more than one lint.
