### ISSUE TITLE
Use CrawlInfo.getRunId() as runid

### ISSUE THREAD

**Issue by sualeh** [adriens/schemacrawler-additional-command-lints-as-csv#4]
Use `CrawlInfo.getRunId()` as runid (from SchemaCrawler 15.01.04 onwards)

**Comment by adriens** [comment]
Hi @sualeh : is it a `UUID` too ?

**Comment by sualeh** [comment]
Yes, this is a UUID.

**Comment by adriens** [comment]
Ok , thanks for pointing this, I'll take a closer look at it hence. Do you have any code snippet on how to get the `CrawnInfo` instance ?

**Comment by sualeh** [comment]
`Catalog.getCrawlInfo().getRunId()`
